[rclone]
args = [
  "--update",
  "--verbose",
  "--transfers 30",
  "--checkers 8",
  "--contimeout 60s",
  "--timeout 300s",
  "--retries 3",
  "--low-level-retries 10",
  "--stats 1s"
]
concurrent_limit = 2

[backup]
remote_name = "GoogleDrive"
root_dir = "Backups/My PC/"
sync_paths = [
  "$XDG_CONFIG_HOME",
  "~/test/test_dir",
  "~/test/test_file",
  "/etc/motd"
]

copy_paths = [
  "~/test_2/1.dat",
  "/etc/motd"
]
